#!/usr/bin/env python

import pwd
import sys
import platform
import os
import re

def config_folder(folder):
    if not os.path.exists(folder):
        os.mkdir(folder)

def config_file(file_path):
    if not os.path.exists(file_path):
        with open(file_path, 'w') as f: f.write("")

def user_prompt():
    return pwd.getpwuid(os.getuid())[0] # Nasty, but best py2.7 way to do it.

def comp_prompt():
    return platform.node()

def login_prompt(user, comp):
    return "@".join((user, comp))

def dir_prompt(uname):
    cwd = os.getcwd()
    homedir = "".join(("/home/", uname))
    if re.match(homedir, cwd):
        cwd = re.sub(homedir, "~", cwd)
    return cwd

def check_status(log_file, new_state):
    new_state_exp = "".join((new_state, "$"))
    with open(log_file, 'r') as f:
        old_state = f.read()
    if re.match(new_state_exp, old_state): return False
    else:
        with open(log_file, 'w') as f: f.write(new_state)
        return True

def main(out):
    uprompt = user_prompt() # Begin by determining current states.
    cprompt = comp_prompt()
    lprompt = login_prompt(uprompt, cprompt)
    dprompt = dir_prompt(uprompt)

    config_dir = "".join(("/home/", uprompt, "/.pyhoc/"))
    config_folder(config_dir) # Make sure the config folder exists.

    udir = "".join((config_dir, ".u")) # Make sure the config files exist.
    cdir = "".join((config_dir, ".c"))
    ldir = "".join((config_dir, ".l"))
    ddir = "".join((config_dir, ".d"))

    for xdir in set([udir, cdir, ldir, ddir]): config_file(xdir)

    ustate = check_status(udir, uprompt) # Determine if the states are new
    cstate = check_status(cdir, cprompt) # True or False
    lstate = check_status(ldir, lprompt)
    dstate = check_status(ddir, dprompt)

    subs = []

    # 0: State newness (true = new), 1: flag 2: output given flag
    subs.append((ustate, "%u", "".join((uprompt, " "))))
    subs.append((ustate, "%U", uprompt))
    subs.append((ustate, "%bu", "".join(("[", uprompt, "] "))))
    subs.append((ustate, "%bU", "".join(("[", uprompt, "]"))))

    subs.append((cstate, "%c", "".join((cprompt, " "))))
    subs.append((cstate, "%C", cprompt))
    subs.append((cstate, "%bc", "".join(("[", cprompt, "] "))))
    subs.append((cstate, "%bC", "".join(("[", cprompt, "]"))))

    subs.append((lstate, "%l", "".join((lprompt, " "))))
    subs.append((lstate, "%L", lprompt))
    subs.append((lstate, "%bl", "".join(("[", lprompt, "] "))))
    subs.append((lstate, "%bL", "".join(("[", lprompt, "]"))))

    subs.append((dstate, "%d", "".join((dprompt, " "))))
    subs.append((dstate, "%D", dprompt))
    subs.append((dstate, "%bd", "".join(("[", dprompt, "] "))))
    subs.append((dstate, "%bD", "".join(("[", dprompt, "]"))))

    for literal in subs: # If state is new, then replace flags accordingly.
        if literal[0]: out = re.sub(literal[1], literal[2], out)
        else: out = re.sub(literal[1], "", out)

    return out

if __name__ == '__main__':
    output = main("".join(sys.argv[1:]))
    sys.stdout.write(output)
